#!/system/bin/sh


echo "==================================="
echo " Sungsonic™HD booting :)"
echo "==================================="


# Wait for system to be "up" before doing other stuff
until [ $(busybox pgrep com.android.systemui) ] ; do
    busybox sleep 1
done